app/site/views.py
# Generic imports from Flask
import socket
from flask import Blueprint, render_template, redirect, abort, session
from flask import request, jsonify, make_response, url_for, flash

# For sending files
from flask import send_from_directory, send_file, safe_join, abort

# Google oAuth api
from authlib.integrations.flask_client import OAuth

# imports for sending alert message
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from twilio.rest import Client
from .email_template import email_template

# useful libraries
from flask_socketio import send
from datetime import datetime
import time
import bcrypt
import random
import json
import pickle
import pandas as pd
import os
from geopy import Nominatim


# custom imports
from .models import *
from app import *

site = Blueprint("site", __name__, template_folder='../templates',
                 static_folder='static', static_url_path='static')

model = pickle.load(open('app/site_data/trained.pkl', 'rb'))

tool = Tools()
User = Users()
work = Workshop()

site_docs = app.config["SITE_DOCS"]
account_sid = app.config["ACCOUNT_SID"]
auth_token = app.config["AUTH_TOKEN"]
google_client_id = app.config['GOOGLE_CLIENT_ID']
google_client_secret = app.config['GOOGLE_CLIENT_SECRET']

# oAuth Setup
google = oauth.register(
    name='google',
    client_id=google_client_id,
    client_secret=google_client_secret,
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_params=None,
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    authorize_params=None,
    api_base_url='https://www.googleapis.com/oauth2/v1/',
    userinfo_endpoint='https://openidconnect.googleapis.com/v1/userinfo',
    client_kwargs={'scope': 'openid email profile'},
)

# USER DEFINED FUNCTIONS
# Map API
def getMapData(username):
    resp = tool.getCompanyDetails(username)
    # print("resp => ", resp[0])
    new_dict = dict()
    for i in range(len(resp)):
        new_dict[resp[i]['City']] = new_dict.get(resp[i]['City'], 0) + 1

    arr = []
    j = 0
    for key, value in new_dict.items():
        arr.append(
            {
                'Name': key,
                'Count': value,
                'region': resp[j]['Region'],
            }
        )
        j += 1

    final_ = [{
        'Company': username,
        'Cities': arr,
    }]

    return final_


# Send Message
def sendMessage(receipent):
    try:
        client = Client(app.config["ACCOUNT_SID"], app.config["AUTH_TOKEN"])
        message = client.messages.create(
            body="Your Hilti tool might require some action. Check mail for more info. -Team HTOT",
            from_='+13312530016',
            to=receipent
        )
        print(message.sid)
    except:
        print("Error while sending message. Try again!")


# Send Email
def sendEmail(username):
    # For Email Module
    try:
        from_mail = app.config["EMAIL_ID"]
        from_passw = app.config["EMAIL_PW"]
        emails = {
            username : 'app/templates/email_templates/user.html'
        }
        for email, template in emails.items():
            message = MIMEMultipart("alternative")
            message['Subject'] = 'HILTI Tool Failure'
            message['From'] = 'HILTI Tools Online Tracking'
            message['To'] = username
            user_template = open(template, 'r')
            user_template = user_template.read()
            template = MIMEText(user_template, 'html')
            message.attach(template)

            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.login(from_mail, from_passw)
            server.sendmail(from_mail, email, message.as_string())
            print("Email sent successfully!")
        server.quit()
    except Exception as error:
        print(error)
        return "<h1> We have following error </h1> <p>{}</p>".format(error)

# Prediction
def prediction(x):
    pred = model.predict([x])
    print('Prediction : ', pred[0])
    if pred[0] == 1:
        try:
            if session:
                print("********************MACHINE FAILURE********************")
                sendEmail(session['EMAIL'])
                response = tool.updateTool("L48433", 'Failure')
                # sendMessage(app.config['PHONE_NUM'])
        except:
            print("Failure predicted, could not send an email..!!!")

# SOCKET IO
@socketio.on('message')
def handle_message(resp):
    print('Message: ', resp)
    x = [resp[0], resp[1], resp[2], resp[3]]
    global nowPointer
    nowPointer = resp[4]
    prediction(x)


@socketio.on('pickupSchedule')
def pickup_schedule(toolid):
    print('pickup =>>>>>>', toolid)
    tool = work.getOneTool(toolid)
    print(tool)
    
    socketio.emit('receivepickupnotification', tool)


# Error Handler
@site.errorhandler(404)
def not_found(error=None):
    message = {
        'status': 404,
        'message': 'Not Found ' + request.url
    }
    resp = jsonify(message)
    return (resp, 200)


############# INDEX ROUTE #############
@site.route("/")
def index():
    try:
        if session:
            return render_template("home.html")
        return render_template("home.html")
    except:
        return render_template("home.html")


@site.route("/dashboard")
def dashboard():
    if session:
        return render_template('dashboard.html')
    return redirect(url_for('site.login'))


@site.route("/workshop/dashboard", methods=["GET", "POST"])
def workshop_dashboard():
    if session:
        tools = work.getToolData()
        if request.method == "POST":
            req = request.form
            if req.get('tool_status') == 'arrived_to_workshop':
                btn_color = 'btn-secondary'
            elif req.get('tool_status') == 'under_repair':
                btn_color = 'btn-danger'
            elif req.get('tool_status') == 'repair_completed':
                btn_color = 'btn-info'
            elif req.get('tool_status') == 'way_to_customer':
                btn_color = 'btn-secondary'
            elif req.get('tool_status') == 'received_by_customer':
                btn_color = 'btn-success'
            else:
                btn_color = 'btn-warning'
            
            update_data = {
                'status_id': req.get('tool_status'),
                'btn_color': btn_color
            }
            Workshop.updateToolData(req.get('hidden_tool_id'),update_data)
            tool_data_count = Workshop.populateWorkshopDashboard()
            return render_template('workshop/workshop_dashboard.html', tools=tools, tool_data_count=tool_data_count)
        else:
            tool_data_count = Workshop.populateWorkshopDashboard()
            return render_template('workshop/workshop_dashboard.html', tools=tools, tool_data_count=tool_data_count)
    return redirect(url_for('site.login'))

@site.route("/workshop/inventory")
def workshop_inventory():
    if session:
        return render_template('workshop/workshop_inventory.html')
    return redirect(url_for('site.login'))


@site.route('/signup', methods=["GET", "POST"])
def signup():
    if session:
        flash("Please logout first", "danger")
        return redirect(url_for('site.index'))
    if request.method == "POST":
        req = request.form

        password = req['password']
        hashed_pw = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt(14))

        u_dict = {
            "company": req['company'],
            "email": req['email'],
            "password": hashed_pw,
            "account_type" : req['account_type']
        }

        if req['password'] == req['cm_password']:
            found = User.getUser(req['email'])
            if found is None:
                flash("Signup successful", "success")
                User.addUser(u_dict, 0)
                return render_template('user/login.html')
            flash("User already exists", "danger")
            return render_template('user/signup.html', u=[])

        flash("Password does not match..!!", 'danger')
        return render_template('user/signup.html', u=u_dict)

    return render_template('user/signup.html', u=[])


@site.route('/login', methods=["GET", "POST"])
def login():
    if session:
        flash("Please logout first", "danger")
        return redirect(url_for('site.index'))
    if request.method == "POST":
        req = request.form
        email = req['email']
        password = req['password']
        status = User.findUser(email, password)
        if status:
            session.clear()
            session['logged_in'] = True
            session['EMAIL'] = status["Email"]
            session['COMPANY'] = status["Company"]
            session['ACCOUNT_TYPE'] = status["account_type"]
            flash("Login successful", "success")

            return redirect(url_for('site.index'))
        elif status == -1:
            flash("Incorrect Email or Password", "danger")
        else:
            flash("User does not exist, Please Sign Up!", "danger")

    return render_template('user/login.html')


# Google oAuth login
@site.route('/google_login')
def google_login():
    google = oauth.create_client('google')
    redirect_uri = url_for('site.authorize', _external=True)
    return google.authorize_redirect(redirect_uri)


# Google oAuth authorize
@site.route('/authorize')
def authorize():
    google = oauth.create_client('google')
    token = google.authorize_access_token()
    resp = google.get('userinfo')
    user_info = resp.json()
    user = oauth.google.userinfo()
    session['profile'] = user_info
    session['EMAIL'] = user_info['email']
    session['logged_in'] = True
    session.permanent = True
    found = User.getUser(user_info['email'])
    if found:
        if found['Company']:
            session['COMPANY'] = found['Company']
        else:
            session['COMPANY'] = 'Company 1'

        return redirect(url_for('site.index'))
    else:
        newuser = {
            'First name': user_info['given_name'],

app/templates/user/login.html
{% extends 'base_template.html' %}
{% block title %} Login Page {% endblock %}

{% block main %}
<div class="wrapper">
    <div class="main-panel panel-newbgcolor" id="main-panel">
        <!-- Navbar -->
        {% include 'navbar.html' %}
        <!-- End Navbar -->
        <div class="panel-header-sm panel-newbgcolor" >
        </div>
        <div class="content pt-5">
                <div class="row justify-content-center">
                    <div class="col-md-6 m-5">
            
                        <h1 class="mb-2">Login</h1>
                        <hr>
                        <div>
                        {% with messages = get_flashed_messages(category_filter=["success"]) %}
                        {% if messages %}
                        {%- for message in messages %}
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            {{message}}
                        {% endfor -%}
                        {% endif %}
                        {% endwith %}

                        {% with messages = get_flashed_messages(category_filter=["danger"]) %}
                        {% if messages %}
                        {%- for message in messages %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            {{message}}
                        {% endfor -%}
                        {% endif %}
                        {% endwith %}
                        </div>
                        <form action="/login" method="POST" id="login_form">
            
                            <div class="form-group">
                                <label>Email</label>
                                <input class="form-control" type="email" name="email">
                            </div>
            
                            <div class="form-group">
                                <label>Password</label>
                                <input class="form-control" type="password" name="password">
                            </div>
                            <div class="pb-3 pt-3">
                                <span>OR Login With 
                                    <a href="{{url_for('site.google_login')}}">
                                        <img class="pl-2" style="height: 25px;" src="../../static/icons/google.svg" alt="Google-icon">
                                    </a>
                                </span>
                            </div>
                            <button type="submit" class="btn btn-primary justify-content-center">Login</button>
            
                        </form>
            
                        <p class="mt-3">New here? <a href="/signup">Create Account</a></p>
            
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}

app/templates/user/signup.html
{% extends 'base_template.html' %}
{% block title %} Login Page {% endblock %}

{% block main %}
<div class="wrapper">
    <div class="main-panel panel-newbgcolor" id="main-panel">
        <!-- Navbar -->
        {% include 'navbar.html' %}
        <!-- End Navbar -->
        <div class="panel-newbgcolor" style="height: 70px;">
        </div>
        <div class="content pt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 m-5">

                    <h1 class="">Sign up</h1>
                    <hr>
                    <div>
                        {% with messages = get_flashed_messages(category_filter=["danger"]) %}
                        {% if messages %}
                        {%- for message in messages %}
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">×</span></button>
                            {{message}}
                        {% endfor -%}
                        {% endif %}
                        {% endwith %}

                    </div>
                        <form action="/signup" method="POST" enctype="multipart/form-data" class="mt-2 p-auto">

                            <div class="form-group">
                                <label>Company Name</label>
                                <input type="text" class="form-control" id="company" name="company" placeholder="{{u['company']}}" value="{{u['company']}}" required>
                            </div>

                            <!-- <div class="form-group">
                                <label>First Name</label>
                                <input type="text" class="form-control" id="company" name="fname" placeholder="{{u['fname']}}" value="{{u['fname']}}" required>
                            </div>

                            <div class="form-group">
                                <label>Last Name</label>
                                <input type="text" class="form-control" id="company" name="lname" placeholder="{{u['lname']}}" value="{{u['fname']}}" required>
                            </div> -->
                            
                            <div class="form-group">
                                <label>Account Type</label>
                                <select class="form-control" id="account_type" name="account_type" required>
                                    <option value='user'>User</option>
                                    <option value='workshop'>Workshop</option>
                                  </select>
                            </div>

                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="{{u['email']}}" value="{{u['email']}}" required>
                            </div>

                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" class="form-control" id="password" name="password" placeholder="" required>
                            </div>

                            <div class="form-group">
                                <label>Confirm Password</label>
                                <input type="password" class="form-control" id="cm_password" name="cm_password" placeholder="" required>
                            </div>

                            <button type="submit" class="btn btn-primary m-auto justify-content-center">Sign up</button>

                        </form>
                        <p class="mt-3">Already a member? <a href="/login">Login</a></p>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

app/templates/user/user_profile.html
{% extends 'base_template.html' %}
{% block link %} {% endblock %}
{% block title %} Dashboard {% endblock %}
{% block main %}
{% include 'sidebar.html' %}

<div class="wrapper panel-newbgcolor">
  <div class="main-panel" id="main-panel">
    <!-- Navbar -->
    {% include 'navbar.html' %}
    <!-- End Navbar -->
    <div class="panel-header panel-header-sm panel-newbgcolor">
    </div>
    <div class="content panel-newbgcolor pt-5">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">
              <h5 class="title">Edit Profile</h5>
            </div>
            <div class="card-body">

              <form action="{{url_for('site.user_profile')}}" method="POST">
                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>Company</label>
                      <input type="text" class="form-control" name="Company" placeholder="Company" value="{{_user['Company']}}">
                    </div>
                  </div>
                  <div class="col-md-6 pl-1">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Email address</label>
                      <input type="email" class="form-control" name="Email" disabled placeholder="Email" value="{{_user['Email']}}">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 pr-1">
                    <div class="form-group">
                      <label>First Name</label>
                      <input type="text" class="form-control" name="First name"  placeholder="{{_user['First name']}}" value="{{_user['First name']}}">
                    </div>
                  </div>
                  <div class="col-md-6 pl-1">
                    <div class="form-group">
                      <label>Last Name</label>
                      <input type="text" class="form-control" name="Last name" placeholder="Last Name" value="{{_user['Last name']}}">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>Address</label>
                      <input type="text" class="form-control" name="Address" placeholder="Work/Home Address"
                        value="{{_user['Address']}}">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-4 pr-1">
                    <div class="form-group">
                      <label>City</label>
                      <input type="text" class="form-control" name="City" placeholder="City" value="{{_user['City']}}">
                    </div>
                  </div>
                  <div class="col-md-4 px-1">
                    <div class="form-group">
                      <label>Country</label>
                      <input type="text" class="form-control" name="Country" placeholder="Country" value="{{_user['Country']}}">
                    </div>
                  </div>
                  <div class="col-md-4 pl-1">
                    <div class="form-group">
                      <label>Postal Code</label>
                      <input type="number" class="form-control" placeholder="ZIP Code" name="Zip_code" value="{{_user['Zip_code']}}">
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <div class="form-group">
                      <label>About Me</label>
                      <textarea rows="4" cols="80" class="form-control" name="Info" placeholder="A few words about you ..."
                        value="{{_user['Info']}}">{{_user['Info']}}</textarea>
                    </div>
                  </div>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-primary">Edit Profile</button>
                </div>
              </form>

            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card card-user">
            <div class="image">
              <img src="https://media.istockphoto.com/videos/low-poly-dark-background-video-id850926774?s=640x640" alt="...">
            </div>
            <div class="card-body">
              <div class="author">
                <a href="#">
                  <img class="avatar border-gray" src="{{_user['Profile pic']}}" alt="Profile Picture">
                  <h5 class="title">{{_user['First Name']}}</h5>
                </a>
                <p class="description">
                  Something
                </p>
              </div>
              <p class="description text-center">
                "HTOT <br>
                A PROJECT FOR <br>
                PREDICTIVE MAINTENENCE"
              </p>
            </div>
            <hr>
            <div class="button-container">
              <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-facebook-f"></i>
              </button>
              <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-twitter"></i>
              </button>
              <button href="#" class="btn btn-neutral btn-icon btn-round btn-lg">
                <i class="fab fa-google-plus-g"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--   Core JS Files   -->
<!-- <script src="../assets/js/core/jquery.min.js"></script>
  <script src="../assets/js/core/popper.min.js"></script>
  <script src="../assets/js/core/bootstrap.min.js"></script>
  <script src="../assets/js/plugins/perfect-scrollbar.jquery.min.js"></script> -->
<!--  Google Maps Plugin    -->
<!-- <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script> -->
<!-- Chart JS -->
<!-- <script src="../assets/js/plugins/chartjs.min.js"></script> -->
<!--  Notifications Plugin    -->
<!-- <script src="../assets/js/plugins/bootstrap-notify.js"></script> -->
<!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
<!-- <script src="../assets/js/now-ui-dashboard.min.js?v=1.5.0" type="text/javascript"></script> -->
<!-- Now Ui Dashboard DEMO methods, don't include it in your project! -->
<!-- <script src="../assets/demo/demo.js"></script> -->

{% endblock %}