app/site/views.py
# Generic imports from Flask
import socket
from flask import Blueprint, render_template, redirect, abort, session
from flask import request, jsonify, make_response, url_for, flash

# For sending files
from flask import send_from_directory, send_file, safe_join, abort

# Google oAuth api
from authlib.integrations.flask_client import OAuth

# imports for sending alert message
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from twilio.rest import Client
from .email_template import email_template

# useful libraries
from flask_socketio import send
from datetime import datetime
import time
import bcrypt
import random
import json
import pickle
import pandas as pd
import os
from geopy import Nominatim


# custom imports
from .models import *
from app import *

site = Blueprint("site", __name__, template_folder='../templates',
                 static_folder='static', static_url_path='static')

model = pickle.load(open('app/site_data/trained.pkl', 'rb'))

tool = Tools()
User = Users()
work = Workshop()

site_docs = app.config["SITE_DOCS"]
account_sid = app.config["ACCOUNT_SID"]
auth_token = app.config["AUTH_TOKEN"]
google_client_id = app.config['GOOGLE_CLIENT_ID']
google_client_secret = app.config['GOOGLE_CLIENT_SECRET']

# oAuth Setup
google = oauth.register(
    name='google',
    client_id=google_client_id,
    client_secret=google_client_secret,
    access_token_url='https://accounts.google.com/o/oauth2/token',
    access_token_params=None,
    authorize_url='https://accounts.google.com/o/oauth2/auth',
    authorize_params=None,
    api_base_url='https://www.googleapis.com/oauth2/v1/',
    userinfo_endpoint='https://openidconnect.googleapis.com/v1/userinfo',
    client_kwargs={'scope': 'openid email profile'},
)

# USER DEFINED FUNCTIONS
# Map API
def getMapData(username):
    resp = tool.getCompanyDetails(username)
    # print("resp => ", resp[0])
    new_dict = dict()
    for i in range(len(resp)):
        new_dict[resp[i]['City']] = new_dict.get(resp[i]['City'], 0) + 1

    arr = []
    j = 0
    for key, value in new_dict.items():
        arr.append(
            {
                'Name': key,
                'Count': value,
                'region': resp[j]['Region'],
            }
        )
        j += 1

    final_ = [{
        'Company': username,
        'Cities': arr,
    }]

    return final_


# Send Message
def sendMessage(receipent):
    try:
        client = Client(app.config["ACCOUNT_SID"], app.config["AUTH_TOKEN"])
        message = client.messages.create(
            body="Your Hilti tool might require some action. Check mail for more info. -Team HTOT",
            from_='+13312530016',
            to=receipent
        )
        print(message.sid)
    except:
        print("Error while sending message. Try again!")


# Send Email
def sendEmail(username):
    # For Email Module
    try:
        from_mail = app.config["EMAIL_ID"]
        from_passw = app.config["EMAIL_PW"]
        emails = {
            username : 'app/templates/email_templates/user.html'
        }
        for email, template in emails.items():
            message = MIMEMultipart("alternative")
            message['Subject'] = 'HILTI Tool Failure'
            message['From'] = 'HILTI Tools Online Tracking'
            message['To'] = username
            user_template = open(template, 'r')
            user_template = user_template.read()
            template = MIMEText(user_template, 'html')
            message.attach(template)

            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.login(from_mail, from_passw)
            server.sendmail(from_mail, email, message.as_string())
            print("Email sent successfully!")
        server.quit()
    except Exception as error:
        print(error)
        return "<h1> We have following error </h1> <p>{}</p>".format(error)

# Prediction
def prediction(x):
    pred = model.predict([x])
    print('Prediction : ', pred[0])
    if pred[0] == 1:
        try:
            if session:
                print("********************MACHINE FAILURE********************")
                sendEmail(session['EMAIL'])
                response = tool.updateTool("L48433", 'Failure')
                # sendMessage(app.config['PHONE_NUM'])
        except:
            print("Failure predicted, could not send an email..!!!")

# SOCKET IO
@socketio.on('message')
def handle_message(resp):
    print('Message: ', resp)
    x = [resp[0], resp[1], resp[2], resp[3]]
    global nowPointer
    nowPointer = resp[4]
    prediction(x)


@socketio.on('pickupSchedule')
def pickup_schedule(toolid):
    print('pickup =>>>>>>', toolid)
    tool = work.getOneTool(toolid)
    print(tool)
    
    socketio.emit('receivepickupnotification', tool)


# Error Handler
@site.errorhandler(404)
def not_found(error=None):
    message = {
        'status': 404,
        'message': 'Not Found ' + request.url
    }
    resp = jsonify(message)
    return (resp, 200)


############# INDEX ROUTE #############
@site.route("/")
def index():
    try:
        if session:
            return render_template("home.html")
        return render_template("home.html")
    except:
        return render_template("home.html")


@site.route("/dashboard")
def dashboard():
    if session:
        return render_template('dashboard.html')
    return redirect(url_for('site.login'))


@site.route("/workshop/dashboard", methods=["GET", "POST"])
def workshop_dashboard():
    if session:
        tools = work.getToolData()
        if request.method == "POST":
            req = request.form
            if req.get('tool_status') == 'arrived_to_workshop':
                btn_color = 'btn-secondary'
            elif req.get('tool_status') == 'under_repair':
                btn_color = 'btn-danger'
            elif req.get('tool_status') == 'repair_completed':
                btn_color = 'btn-info'
            elif req.get('tool_status') == 'way_to_customer':
                btn_color = 'btn-secondary'
            elif req.get('tool_status') == 'received_by_customer':
                btn_color = 'btn-success'
            else:
                btn_color = 'btn-warning'
            
            update_data = {
                'status_id': req.get('tool_status'),
                'btn_color': btn_color
            }
            Workshop.updateToolData(req.get('hidden_tool_id'),update_data)
            tool_data_count = Workshop.populateWorkshopDashboard()
            return render_template('workshop/workshop_dashboard.html', tools=tools, tool_data_count=tool_data_count)
        else:
            tool_data_count = Workshop.populateWorkshopDashboard()
            return render_template('workshop/workshop_dashboard.html', tools=tools, tool_data_count=tool_data_count)
    return redirect(url_for('site.login'))

@site.route("/workshop/inventory")
def workshop_inventory():
    if session:
        return render_template('workshop/workshop_inventory.html')
    return redirect(url_for('site.login'))


@site.route('/signup', methods=["GET", "POST"])
def signup():
    if session:
        flash("Please logout first", "danger")
        return redirect(url_for('site.index'))
    if request.method == "POST":
        req = request.form

        password = req['password']
        hashed_pw = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt(14))

        u_dict = {
            "company": req['company'],
            "email": req['email'],
            "password": hashed_pw,
            "account_type" : req['account_type']
        }

        if req['password'] == req['cm_password']:
            found = User.getUser(req['email'])
            if found is None:
                flash("Signup successful", "success")
                User.addUser(u_dict, 0)
                return render_template('user/login.html')
            flash("User already exists", "danger")
            return render_template('user/signup.html', u=[])

        flash("Password does not match..!!", 'danger')
        return render_template('user/signup.html', u=u_dict)

    return render_template('user/signup.html', u=[])


@site.route('/login', methods=["GET", "POST"])
def login():
    if session:
        flash("Please logout first", "danger")
        return redirect(url_for('site.index'))
    if request.method == "POST":
        req = request.form
        email = req['email']
        password = req['password']
        status = User.findUser(email, password)
        if status:
            session.clear()
            session['logged_in'] = True
            session['EMAIL'] = status["Email"]
            session['COMPANY'] = status["Company"]
            session['ACCOUNT_TYPE'] = status["account_type"]
            flash("Login successful", "success")

            return redirect(url_for('site.index'))
        elif status == -1:
            flash("Incorrect Email or Password", "danger")
        else:
            flash("User does not exist, Please Sign Up!", "danger")

    return render_template('user/login.html')


# Google oAuth login
@site.route('/google_login')
def google_login():
    google = oauth.create_client('google')
    redirect_uri = url_for('site.authorize', _external=True)
    return google.authorize_redirect(redirect_uri)


# Google oAuth authorize
@site.route('/authorize')
def authorize():
    google = oauth.create_client('google')
    token = google.authorize_access_token()
    resp = google.get('userinfo')
    user_info = resp.json()
    user = oauth.google.userinfo()
    session['profile'] = user_info
    session['EMAIL'] = user_info['email']
    session['logged_in'] = True
    session.permanent = True
    found = User.getUser(user_info['email'])
    if found:
        if found['Company']:
            session['COMPANY'] = found['Company']
        else:
            session['COMPANY'] = 'Company 1'

        return redirect(url_for('site.index'))
    else:
        newuser = {
            'First name': user_info['given_name'],

app/templates/base_template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" /> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Material Kit CSS -->
    <link href="{{url_for('static',filename='assets/css/bootstrap.min.css')}}" rel="stylesheet" />

    <!-- <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}" /> -->
    <link rel="stylesheet" href="{{url_for('static',filename='assets/css/now-ui-dashboard.css')}}">

    <!-- Fonts and icons -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous"/>

    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous">

    <!-- Prevent favicon 404 error -->
    <link rel="icon" href="data:,">

    {% block links %}   {% endblock %}
    <title>{% block title %} {% endblock %} | HILTI-SCC</title>
</head>

<body>
    {% include 'sidebar.html' %}
    <main>{% block main %}{% endblock %}</main>
    <main>{% block login %}{% endblock %}</main>

    <footer class="footer panel-newbgcolor">
        <div class="container-fluid ">
          <nav>
          </nav>
          <div class="copyright" id="copyright">
            &copy;
            <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Designed by <a href="" target="_blank">HTOT</a>. Coded by <a href="https://github.com/Shounak-Pattewale" target="_blank">Shounak</a> & 
            <a href="https://github.com/taha20181" target="_blank">Taha</a>.
          </div>
        </div>
      </footer>

    <script src="{{url_for('static',filename='assets/js/core/jquery.min.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='assets/js/core/popper.min.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='assets/js/core/bootstrap.min.js')}}" type="text/javascript"></script>
    <script src="{{url_for('static',filename='assets/js/plugins/perfect-scrollbar.jquery.min.js')}}" type="text/javascript"></script>
    
    <!-- Font-awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" crossorigin="anonymous">

    <!-- Charlist-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
    <script src="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="{{url_for('static',filename='assets/js/plugins/bootstrap-notify.js')}}"></script>
    
    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="{{url_for('static',filename='assets/js/now-ui-dashboard.js')}}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- amCHART links -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
    integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
    crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"> </script>
    <!-- Resources -->
    <script src="https://cdn.amcharts.com/lib/4/core.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/dark.js"></script>
    <script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>

    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.1.1/dist/chart.js"></script>

    <!-- HighCharts CDN -->
    <script src="https://code.highcharts.com/stock/highstock.js"></script>
    <script src="https://code.highcharts.com/stock/modules/data.js"></script>
    <script src="https://code.highcharts.com/stock/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/stock/modules/export-data.js"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='tool_data.js') }}"></script>

    <style>
        #chartdiv {
            width: 100%;
            height: 450px;
        }

        #myChart4 {
            width: 100%;
            height: 200px;
        }

        text tspan {
            font-size: 65%;
        }
    </style>

    {% block script %}{% endblock %}

</body>

</html>

app/templates/map.html
{% extends 'base_template.html' %}

{% block link %}
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
<!--     Fonts and icons     -->
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<!-- CSS Files -->
<link href="../assets/css/bootstrap.min.css" rel="stylesheet" />
<link href="../assets/css/now-ui-dashboard.css?v=1.5.0" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/styles.css') }}">
{% endblock %}

{% block title %}
Tool Location
{% endblock %}

{% block main %}
{% include 'sidebar.html' %}
<div class="wrapper ">
        <div class="main-panel" id="main-panel">
                <!-- Navbar -->
                {% include 'navbar.html' %}
                <!-- End Navbar -->
                <div class="panel-header panel-header-sm">
                </div>
                <div class="content">
                        <div class="row">
                                <div class="col-md-12">
                                        <div class="card ">
                                                <div class="card-header ">
                                                        Google Maps
                                                </div>
                                                <div class="card-body ">
                                                        <div id="map" class="map"></div>
                                                </div>
                                        </div>
                                </div>
                                {% include 'tables.html' %}
                        </div>
                </div>
        </div>
</div>
{% endblock %}

{% block script %}
<script>
  // console.log({{mapdb}});
</script>
<script src="{{ url_for('static', filename='map_data.js') }}"></script>
<script src="{{ url_for('static', filename='assets/js/index.js') }}"></script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLew1RrPesyP9dC9yI907tMzMU4H_Gz0g&callback=initMap">
        </script>
{% endblock %}

app/templates/navbar.html
{% set active_page = url_for(request.endpoint) %}
{% set navigation_bar = [
('/', 'Home Page'),
('/dashboard', 'Dashboard'),
('/user_profile', 'User Profile'),
('/history','Tool History'),
('/login','Login'),
('/signup','Signup'),
('/tool_location', 'Tool Location'),
('/manage_tools', 'Manage Tools')
] -%}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg  navbar-absolute nav-newbgcolor">

  <div class="container-fluid">
    <div class="navbar-wrapper">
      <div class="navbar-toggle">
        <button type="button" class="navbar-toggler">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>

      {% for href, caption in navigation_bar %}
      {% if href == active_page %}
      <a class="navbar-brand" style=" font-size: 120%; font-weight: 700;">{{caption|e}}</a>
      {% endif %}
      {% endfor %}

    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
      aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <!-- <form>
        <div class="input-group no-border" style="color: black;">
          <input type="text" value="" class="form-control" placeholder="Search...">
          <div class="input-group-append">
            <div class="input-group-text">
              <i class="now-ui-icons ui-1_zoom-bold" style="color: black;"></i>
            </div>
          </div>
        </div>
      </form> -->
      <div style="padding-top: 5px;">
        <ul class="navbar-nav">
          <li class="nav-item">
            {% if session['logged_in']==True %}
              {% if session['ACCOUNT_TYPE']=='user' %}
                <a class="nav-link" href="{{url_for('site.get_report')}}">
                  <i class="now-ui-icons arrows-1_cloud-download-93"></i>
                  <p>
                    <span class="d-lg-block d-md-block">Download Stats</span>
                  </p>
                </a>
              {% endif %}
            {% endif %}
          </li>

          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="now-ui-icons location_world"></i>
              <p>
                <span class="d-lg-block d-md-block">Some Actions</span>
              </p>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Daily</a>
              <a class="dropdown-item" href="#">Weekly</a>
              <a class="dropdown-item" href="#">Monthly</a>
            </div>
          </li> -->

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="now-ui-icons users_single-02"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              {% if session['logged_in']==True %}
              <a class="dropdown-item" href="{{url_for('site.logout')}}">Logout</a>
              {% else %}
              <a class="dropdown-item" href="{{url_for('site.signup')}}">Signup</a>
              <a class="dropdown-item" href="{{url_for('site.login')}}">Login</a>
              {% endif %}
            </div>

          </li>
        </ul>
      </div>

    </div>
  </div>
</nav>
<!-- End Navbar -->

app/templates/sidebar.html
{% set active_page = url_for(request.endpoint) %}

<div class="wrapper" style="position: absolute;">
    <div class="sidebar">
        <div class="logo">
            <a href="{{ url_for('site.index') }}" class="simple-text logo-mini">
                HILTI
            </a>
            <a href="{{ url_for('site.index') }}" class="simple-text logo-normal">
                HTOT
            </a>
        </div>

        <div class="sidebar-wrapper" id="sidebar-wrapper">
            <ul class="nav">

                <li {% if active_page=="/" %} class="active" style="color: #141E30;" {%endif %}>
                    <a href="{{ url_for('site.index') }}">
                        {% if active_page == "/" %}
                        <i class="fas fa-home" style="color: #141E30;"></i>
                        <p style="color: #141E30;">Home</p>
                        {% else %}
                        <i class="fas fa-home"></i>
                        <p>Home</p>
                        {% endif %}
                    </a>
                </li>

                {% if session['logged_in']==True %}
                    {% if session['ACCOUNT_TYPE'] == 'workshop' %}
                    <li {% if active_page=="/workshop/dashboard" %} class="active" {% endif %}>
                        <a href="{{ url_for('site.workshop_dashboard') }}">
                            {% if active_page == "/workshop/dashboard" %}
                            <i class="now-ui-icons business_chart-bar-32" style="color: #141E30;"></i>
                            <p style="color: #141E30;">Workshop Dashboard </p>
                            {% else %}
                            <i class="now-ui-icons business_chart-bar-32"></i>
                            <p>Dashboard</p>
                            {% endif %}
                        </a>
                    </li>
                    <li {% if active_page=="/workshop/inventory" %} class="active" {% endif %}>
                        <a href="{{url_for('site.workshop_inventory')}}">

                            {% if active_page == "/workshop/inventory" %}
                            <i class="fas fa-chalkboard" style="color: #141E30;"></i>
                            <p style="color: #141E30;">Workshop Inventory</p>
                            {% else %}
                            <i class="fas fa-chalkboard"></i>
                            <p>Workshop Inventory</p>
                            {% endif %}
                        </a>
                    </li>
                    {% else %}
                    <li {% if active_page=="/user_profile" %} class="active" {% endif %}>
                        <a href="{{ url_for('site.user_profile') }}">
                            {% if active_page == "/user_profile" %}
                            <i class="far fa-user" style="color: #141E30;"></i>
                            <p style="color: #141E30;">User Profile</p>
                            {% else %}
                            <i class="far fa-user"></i>
                            <p>User Profile</p>
                            {% endif %}
                        </a>
                    </li>

                    <li {% if active_page=="/dashboard" %} class="active" {% endif %}>
                        <a href="{{ url_for('site.dashboard') }}">
                            {% if active_page == "/dashboard" %}
                            <i class="now-ui-icons business_chart-bar-32" style="color: #141E30;"></i>
                            <p style="color: #141E30;">Dashboard </p>
                            {% else %}
                            <i class="now-ui-icons business_chart-bar-32"></i>
                            <p>Dashboard</p>
                            {% endif %}
                        </a>
                    </li>

                    <li {% if active_page=="/manage_tools" %} class="active" {% endif %}>
                        <a href="{{ url_for('site.manage_tools') }}">
                            {% if active_page == "/manage_tools" %}
                            <i class="fas fa-tasks" style="color: #141E30;"></i>
                            <p style="color: #141E30;">Manage Tools</p>
                            {% else %}
                            <i class="fas fa-tasks"></i>
                            <p>Manage Tools</p>
                            {% endif %}
                        </a>
                    </li>
                    {% endif %}
                    
                {% else %}

                <li {% if active_page=="/login" %} class="active" {% endif %}>
                    <a href="{{url_for('site.login')}}">

                        {% if active_page == "/login" %}
                        <i class="now-ui-icons gestures_tap-01" style="color: #141E30;"></i>
                        <p style="color: #141E30;">Login</p>
                        {% else %}
                        <i class="now-ui-icons gestures_tap-01"></i>
                        <p>Login</p>
                        {% endif %}
                    </a>
                </li>

                <li {% if active_page=="/signup" %} class="active" {% endif %}>
                    <a href="{{url_for('site.signup')}}">

                        {% if active_page == "/signup" %}
                        <i class="now-ui-icons business_badge" style="color: #141E30;"></i>
                        <p style="color: #141E30;">Signup</p>
                        {% else %}
                        <i class="now-ui-icons business_badge"></i>
                        <p>Signup</p>
                        {% endif %}
                    </a>
                </li>

                {% endif %}

            </ul>
        </div>
    </div>
</div>

app/templates/timeline.html
{% block links %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='assets/css/timeline.css') }}">
{% endblock %}

{% block main %}

        <div class="">
            <div class="">
                <div class="">
                    <div class="">
                        <div class="card-header ">
                            <h5 style="margin-bottom: 0 !important;">L43245</h5>
                        </div>
                        <div class="card-body ">
                            <div class="container">
                                <ul>
                                    <li><span></span>
                                        <div>
                                            <div class="title">Pick up scheduled</div>
                                            <div class="info"></div>
                                            <div class="type">20th Aug '21</div>
                                        </div> <span class="number completed"><span>10:00</span> <span>12:00</span></span>
                                    </li>
                                    <li>
                                        <div><span></span>
                                            <div class="title">Received at Workshop</div>
                                            <div class="info"></div>
                                            <div class="type">20th Aug '21</div>
                                        </div> <span class="number completed"><span>13:00</span> <span>14:00</span></span>
                                    </li>
                                    <li>
                                        <div><span></span>
                                            <div class="title">In service</div>
                                            <div class="info"></div>
                                            <div class="type">20th Aug '21</div>
                                        </div> <span class="number completed"><span>15:00</span> <span>17:45</span></span>
                                    </li>
                                    <li>
                                        <div><span></span>
                                            <div class="title">Dispatched from workshop</div>
                                            <!-- <div class="info">Let&apos;s make coolest things in css</div> -->
                                            <!-- <div class="type">Review</div> -->
                                        </div> <span class="number"><span>15:00</span> <span>17:45</span></span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}